- name: Test with pytest
      # 1. 將工作目錄設定為包含 lms_log_analyzer 和 tests 的父目錄
      working-directory: ./MCP_lms_log_analyzer/EDGE-codex-refactor-lms_log_analyzer_v2-into-modular-project
      run: |
        # 2. 將包含 src 的 lms_log_analyzer 目錄加入 PYTHONPATH
        export PYTHONPATH=$PYTHONPATH:./lms_log_analyzer
        # (除錯用) 列出當前目錄的檔案，您應該能看到 lms_log_analyzer/
        echo "--- Listing files in correct working directory ---"
        ls -R
        echo "------------------------------------------------"
        # 3. 執行 pytest，並明確指向 tests 目錄
        pytest ./lms_log_analyzer/tests/