# .github/workflows/python-app.yml

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      # 在專案根目錄執行，但指向正確的 requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r ./MCP_lms_log_analyzer/EDGE-codex-refactor-lms_log_analyzer_v2-into-modular-project/lms_log_analyzer/requirements.txt
        pip install pytest  # 確保 pytest 已安裝

    - name: Test with pytest
      # 進入正確的子目錄，然後設定 PYTHONPATH 並執行 pytest
      working-directory: ./MCP_lms_log_analyzer/EDGE-codex-refactor-lms_log_analyzer_v2-into-modular-project/lms_log_analyzer
      run: |
        # 將當前目錄(lms_log_analyzer)加入 PYTHONPATH，這樣 Python 才能找到 src/
        export PYTHONPATH=$PYTHONPATH:.
        pytest