name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      # 在專案根目錄執行，但指向正確的 requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r ./MCP_lms_log_analyzer/EDGE-codex-refactor-lms_log_analyzer_v2-into-modular-project/lms_log_analyzer/requirements.txt
        pip install pytest  # 確保 pytest 已安裝

    - name: Test with pytest
      # 1. 將工作目錄設定為包含 lms_log_analyzer 和 tests 的父目錄
      working-directory: ./MCP_lms_log_analyzer/EDGE-codex-refactor-lms_log_analyzer_v2-into-modular-project
      run: |
        # 2. 將包含 src 的 lms_log_analyzer 目錄加入 PYTHONPATH
        export PYTHONPATH=$PYTHONPATH:./lms_log_analyzer
        # (除錯用) 列出當前目錄的檔案，您應該能看到 lms_log_analyzer/
        echo "--- Listing files in correct working directory ---"
        ls -R
        echo "------------------------------------------------"
        # 3. 執行 pytest，並明確指向 tests 目錄
        pytest ./lms_log_analyzer/tests/