name: Python package

on:
  push:
    branches: [ "main", "work" ]
  pull_request:
    branches: [ "main", "work" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd MCP_lms_log_analyzer/EDGE-codex-refactor-lms_log_analyzer_v2-into-modular-project
        python -m pip install --upgrade pip
        pip install -r lms_log_analyzer/requirements.txt
        pip install pytest
    - name: Run tests
      run: |
        cd MCP_lms_log_analyzer/EDGE-codex-refactor-lms_log_analyzer_v2-into-modular-project
        pytest -q tests
